### ISSUE TITLE
No module yaml

### ISSUE THREAD

**Issue by jernst** [uboslinux/ubos-packages#13]
When attempting to backup to S3:

```
[root@ubos-raspberry-pi2 shepherd]# ubos-admin backup-to-amazon-s3
No Amazon credentials found in /etc/amazons3/aws-config-for-backup. To set this up, please provide the following information:
Amazon AWS access key id: xxx
Amazon AWS secret access key: yyy
ERROR: Traceback (most recent call last):
  File "/usr/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/lib/python3.6/site-packages/awscli/clidriver.py", line 55, in main
    driver = create_clidriver()
  File "/usr/lib/python3.6/site-packages/awscli/clidriver.py", line 64, in create_clidriver
    event_hooks=emitter)
  File "/usr/lib/python3.6/site-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/usr/lib/python3.6/site-packages/awscli/plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "/usr/lib/python3.6/site-packages/awscli/handlers.py", line 27, in <module>
    from awscli.customizations.cloudformation import initialize as cloudformation_init
  File "/usr/lib/python3.6/site-packages/awscli/customizations/cloudformation/__init__.py", line 13, in <module>
    from awscli.customizations.cloudformation.package import PackageCommand
  File "/usr/lib/python3.6/site-packages/awscli/customizations/cloudformation/package.py", line 23, in <module>
    from awscli.customizations.cloudformation.artifact_exporter import Template
  File "/usr/lib/python3.6/site-packages/awscli/customizations/cloudformation/artifact_exporter.py", line 25, in <module>
    from awscli.customizations.cloudformation.yamlhelper import yaml_dump, \
  File "/usr/lib/python3.6/site-packages/awscli/customizations/cloudformation/yamlhelper.py", line 14, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by jernst** [comment]
Still there. We need module `python-yaml`.
